services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: filacero
      POSTGRES_PASSWORD: filacero
      POSTGRES_DB: filacero_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 
  